main: ru.empireprojekt.empireitems.EmpireItems
name: EmpireItems
version: ${project.version}
author: RatushevRoman
api-version: 1.13
commands:
  empireitems:
    usage: |
      /empireitems reload - Перезагружает плагин