main: ru.empireprojekt.empireitems.EmpireItems
name: EmpireItems
version: 2.2
author: RatushevRoman
api-version: 1.13
softdepend: [DiscordSRV,PlaceholderAPI,Item-NBT-API]
depend: []
commands:
  ereload:
  emsplash:
  emreplace:
  emp:
  emr:
  emgui:
  ezip:
  thirst:
  emojis:
  emnbt:
  emrepair:
  empireitems:
    usage: |
      /ereload - Перезагружает плагин
      /emp give - дает предмет
      /ezip - создает архив
